# Generated by Django 3.1 on 2021-11-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211110_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory'),
        ),
    ]
